apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- kubeflow-dashboard-rbac.yaml
- auth-proxy-configmap.yaml

patches:
- path: mod-arch-ui-deployment.yaml
  target:
    group: apps
    kind: Deployment
    name: mod-arch-ui
    version: v1
- path: mod-arch-ui-service.yaml
  target:
    group: apps
    kind: Service
    name: mod-arch-service
    version: v1
namespace: kubeflow
