apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: mod-arch-ui
  labels:
    app: mod-arch-ui
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account
  selector:
    matchLabels:
      app: mod-arch-ui
