apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: mod-arch-ui
  labels:
    app: mod-arch-ui
spec:
  host: mod-arch-ui-service.kubeflow.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
