apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../kubeflow
- virtual-service.yaml
- destination-rule-ui.yaml
- authorization-policy-ui.yaml

patches:
  - path: mod-arch-ui-service.yaml
    target:
      version: v1
      kind: Service
      name: mod-arch-ui-service

namespace: kubeflow