apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mod-arch-ui
  labels:
    app: mod-arch-ui
spec:
  gateways:
  - kubeflow-gateway
  hosts:
  - '*'
  http:
  - headers:
      request:
        add:
          x-forwarded-prefix: /mod-arch
    match:
    - uri:
        prefix: /mod-arch/
    rewrite:
      uri: /
    route:
    - destination:
        host: mod-arch-ui-service.kubeflow.svc.cluster.local
        port:
          number: 80
