---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mod-arch-ui-services-reader
rules:
- apiGroups:
    - ''
  resources:
    - services
  verbs:
    - get
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mod-arch-ui-services-reader-binding
subjects:
- kind: ServiceAccount
  name: mod-arch-ui
roleRef:
  kind: ClusterRole
  name: mod-arch-ui-services-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mod-arch-retrieve-clusterrolebindings
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mod-arch-retrieve-clusterrolebindings-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mod-arch-retrieve-clusterrolebindings
subjects:
- kind: ServiceAccount
  name: mod-arch-ui
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mod-arch-create-sars
rules:
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mod-arch-create-sars-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mod-arch-create-sars
subjects:
- kind: ServiceAccount
  name: mod-arch-ui
