apiVersion: v1
kind: Service
metadata:
  name: mod-arch-ui-service
  labels:
    app: mod-arch-ui
    run: mod-arch-ui
spec:
  selector:
    app: mod-arch-ui
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: ClusterIP
